---
- hosts: 172.31.35.9
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myvariable

    #register is keyword not a varibale

  - name: I want to display first task result
    debug:
      msg: "{{myvariable}}"