---
- hosts: 172.31.35.9
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      name: tree
      state: present
    ignore_errors: yes

  - name: install wget
    apt:
      name: wget
      state: present