---
- hosts: 172.31.35.9
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu nodes
    apt:
      name: apache2
      state: present

  - name: copy myindex.html file into node side
    copy:
      src: myindex.html
      dest: /var/www/html/index.html

  - name: copy myindex.j2 file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restartedwebserver

  - name: I want to download remote(internet) files
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted