---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ubantu
    apt:
       name: apache2
       state: present

  - name: i want to start webserver on ubantu
    service:
      name: apache2
      state: start     

  # apt-get install apache2
  # service apache2 apache2