---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start webserver on ubuntu nodes
    service:
      name: apache2
      start: started
    when: ansible_os_family == "Debian"
